// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6Lh5PcR3KxJlYGVx7mZnzCkU_CyFy5o',
    appId: '1:206192329935:web:acadda283eb66ef278a3ba',
    messagingSenderId: '206192329935',
    projectId: 'scrummies-384d5',
    authDomain: 'scrummies-384d5.firebaseapp.com',
    storageBucket: 'scrummies-384d5.appspot.com',
    measurementId: 'G-EZXN017P69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJjhcJ09zpjj6Vdd_93Z0w23Se5IeQSA',
    appId: '1:206192329935:android:ffa7371bcf8680dd78a3ba',
    messagingSenderId: '206192329935',
    projectId: 'scrummies-384d5',
    storageBucket: 'scrummies-384d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0LFJhH0bXlB-VQUJlyTZUd9nu3aTDBBY',
    appId: '1:206192329935:ios:924b1c832afe137878a3ba',
    messagingSenderId: '206192329935',
    projectId: 'scrummies-384d5',
    storageBucket: 'scrummies-384d5.appspot.com',
    iosBundleId: 'com.example.cp3405Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0LFJhH0bXlB-VQUJlyTZUd9nu3aTDBBY',
    appId: '1:206192329935:ios:d86269eed78da0d078a3ba',
    messagingSenderId: '206192329935',
    projectId: 'scrummies-384d5',
    storageBucket: 'scrummies-384d5.appspot.com',
    iosBundleId: 'com.example.cp3405Project.RunnerTests',
  );
}
